apiVersion: v1
kind: Service

metadata:
  name: cyber-recon-service

spec:
  type: NodePort

  selector:
    app: cyber-recon

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007